server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: feature-query-service
  
  # Redis配置 (热数据存储)
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 50
        min-idle: 10
        max-wait: 3000ms
  
  # Kafka配置
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
    consumer:
      group-id: feature-query-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000ms

# 特征中心自定义配置
featurehub:
  # KeeWiDB配置 (冷数据存储)
  keewidb:
    host: localhost
    port: 6380
    password: 
    database: 0
    timeout: 5000ms
  
  # 元数据服务配置
  metadata-service:
    base-url: http://localhost:8081
    timeout: 5000
  
  # Kafka主题配置
  kafka:
    query-log-topic: feature-query-logs
  
  # 查询配置
  query:
    default-timeout-ms: 5000
    batch-size-limit: 1000
    enable-async-metadata-update: true

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    com.featurehub: INFO
    org.springframework.kafka: WARN
    org.springframework.data.redis: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/feature-query-service.log
    max-size: 100MB
    max-history: 30

# 应用信息
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@' 